module.exports = {
  code: 1,
  message: '',
  result: [{
    'repeat(5,10)': {
      request: '{{request()}}',
      index: '{{index()}}',
      id: '{{id()}}',
      bool: '{{bool()}}',
      integer: '{{integer()}}',
      float: '{{float()}}',
      string: '{{string()}}',
      random: '{{random(\'张三\',\'李四\',\'王五\',\'赵六\',\'田七\',\'王八\',\'小九九\')}}',
      name: '{{name()}}',
      age: '{{age()}}',
      gender: '{{gender()}}',
      email: '{{email()}}',
      phone: '{{phone()}}',
      username: '{{username()}}',
      password: '{{password()}}',
      region: '{{region()}}',
      province: '{{province()}}',
      city: '{{city()}}',
      county: '{{county()}}',
      address: '{{address()}}',
      zip: '{{zip()}}',
      longitude: '{{longitude()}}',
      latitude: '{{latitude()}}',
      url: '{{url()}}',
      ua: '{{ua()}}',
      ip: '{{ip()}}',
      mac: '{{mac()}}',
      avatar: '{{avatar()}}',
      image: '{{image()}}',
      color: '{{color()}}',
      rgb: '{{rgb()}}',
      rgba: '{{rgba()}}',
      date: '{{date()}}',
      time: '{{time()}}',
      datetime: '{{datetime()}}',
      title: '{{title()}}',
      paragraph: '{{paragraph()}}',
      sentence: '{{sentence()}}'
    }
  }]
}
